-- Migration 001: Create nostr_hitl table
-- Single source of truth for all HITL events in Nodus OS
-- Designed for protocol alignment, signature traceability, and multi-tenant isolation

CREATE TABLE IF NOT EXISTS nostr_hitl (
    -- Nostr identity
    event_id       TEXT PRIMARY KEY,                  -- Unique event ID (e.g., hitl_abc123def456)
    kind           INTEGER NOT NULL DEFAULT 10003,    -- Nostr kind: 10003 (request), 10020 (inbox), 10100 (recording)
    pubkey         TEXT NOT NULL DEFAULT 'hitl-hub',  -- Publisher's pubkey hex

    -- Correlation
    session_id     TEXT,                              -- Session/correlation tag from Nostr event
    reference_id   TEXT,                              -- References another event (e.g., 10004 refs 10003)
    dw_pubkey      TEXT,                              -- Digital Worker pubkey (for filtering)
    owner_pubkey   TEXT,                              -- Tenant/user pubkey from Nostr

    -- User targeting
    user_id        TEXT NOT NULL,                     -- Backoffice user ID who must approve
    tenant_id      TEXT DEFAULT 'default',             -- Multi-tenant isolation

    -- Content
    content        TEXT,                              -- Raw Nostr event content (JSON)
    hint           TEXT,                              -- Human-readable hint for the user
    action         TEXT,                              -- Action type: send_email, deploy_sensor, start_recording, etc.
    payload        JSONB DEFAULT '{}'::jsonb,         -- Structured payload (action_details, context, metadata)
    tags           JSONB DEFAULT '[]'::jsonb,         -- Nostr tags array

    -- Lifecycle
    status         TEXT NOT NULL DEFAULT 'pending',    -- pending | approved | rejected | expired
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at    TIMESTAMPTZ,                        -- Set on approve/reject/expire
    expires_at     TIMESTAMPTZ,                        -- Auto-expiry timestamp (default: created_at + 5 min)

    -- Signature traceability
    sig            TEXT,                               -- Nostr event signature (64-byte hex, Schnorr)
    verified       BOOLEAN DEFAULT false,             -- Signature verified flag
    relay_url      TEXT                               -- Origin relay URL
);

-- Indexes for fast querying.
-- NOTE: only indexes on columns guaranteed to exist are created here. When the
-- table pre-exists with llibreta-v2's schema (migration 017), hub-only columns
-- (user_id, tenant_id, expires_at) are added by migration 002, which also
-- creates the indexes that depend on them.
CREATE INDEX IF NOT EXISTS idx_nostr_hitl_session
    ON nostr_hitl(session_id, kind);

CREATE INDEX IF NOT EXISTS idx_nostr_hitl_dw
    ON nostr_hitl(dw_pubkey, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_nostr_hitl_kind_status
    ON nostr_hitl(kind, status);

-- Comments
COMMENT ON TABLE nostr_hitl IS
    'Single source of truth for all HITL events in Nodus OS. Supports Nostr protocol alignment (kind:10003/10020/10100), signature traceability, and cross-tenant filtering.';

COMMENT ON COLUMN nostr_hitl.event_id IS 'Unique HITL event ID (generated by HITL Hub)';
COMMENT ON COLUMN nostr_hitl.kind IS 'Nostr event kind: 10003 (HITL request), 10020 (async inbox), 10100 (recording result)';
COMMENT ON COLUMN nostr_hitl.action IS 'Action type: send_email, create_calendar_event, deploy_sensor, start_recording, etc.';
COMMENT ON COLUMN nostr_hitl.status IS 'Lifecycle status: pending, approved, rejected, expired';
